trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  AZURE_CONTAINER_APP_NAME: 'gateway-global-integration-ui-iac'
  RESOURCE_GROUP: 'Gateway-Resources-IAC'
  DOCKER_IMAGE: 'attonbomb/systemadmin:latest'  # Replace with your Docker Hub image path
  AZURE_SUBSCRIPTION: 'Gateway-Resources-IAC-MI-Conn-2'

steps:
  - task: Docker@2
    inputs:
      command: 'login'
      containerRegistry: 'attonbomb-DockerHub-SC'
  
  # Set the Azure subscription based on the branch
  - script: |
      echo "Determining Azure subscription..."
      if [ "$(Build.SourceBranchName)" = "development" ]; then
        echo "##vso[task.setvariable variable=AZURE_SUBSCRIPTION]Dev-Gateway-Resources-MS"
        echo "##vso[task.setvariable variable=DOCKER_IMAGE]attonbomb/systemadmin:develop"
      else
        echo "##vso[task.setvariable variable=AZURE_SUBSCRIPTION]Gateway-Resources-IAC-MI-Conn-2"
      fi
    displayName: 'Set Azure Subscription'

  - task: AzureCLI@2
    inputs:
      azureSubscription: $(AZURE_SUBSCRIPTION)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo "Updating Azure Container App with the latest image"
        az config set extension.use_dynamic_install=yes_without_prompt
        
        # Update the Azure Container App to pull the latest image
        az containerapp update \
          --name gateway-global-integration-ui-iac
          --resource-group Gateway-IAC-Resources
          --image attonbomb/systemadmin:latest
          --registry-server hub.docker.com

        echo "Global Integration API Container App updated successfully"

